-- =============================================================================
-- Sistema AgTech de Gestión y Optimización de Lotes de Cultivo
-- Trabajo Final Integrador (TFI) - Grupo 107
-- DDL de Creación de Esquema de Base de Datos
-- Compatible con: H2 Database (Perfil dev) y PostgreSQL (Perfil prod)
-- =============================================================================

-- Eliminación de tablas en orden inverso de dependencias (limpieza de entorno)
DROP TABLE IF EXISTS labor_insumo CASCADE;
DROP TABLE IF EXISTS detalle_compra CASCADE;
DROP TABLE IF EXISTS movimiento_stock CASCADE;
DROP TABLE IF EXISTS compra_insumo CASCADE;
DROP TABLE IF EXISTS registro_cosecha CASCADE;
DROP TABLE IF EXISTS labor_agricola CASCADE;
DROP TABLE IF EXISTS registro_mantenimiento CASCADE;
DROP TABLE IF EXISTS regla_climatica CASCADE;
DROP TABLE IF EXISTS maquinaria CASCADE;
DROP TABLE IF EXISTS insumo CASCADE;
DROP TABLE IF EXISTS lote CASCADE;
DROP TABLE IF EXISTS cultivo CASCADE;
DROP TABLE IF EXISTS proveedor CASCADE;
DROP TABLE IF EXISTS usuario CASCADE;

-- -----------------------------------------------------------------------------
-- 0. Tablas de Catálogos y Usuarios
-- -----------------------------------------------------------------------------
CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    rol VARCHAR(30) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    CONSTRAINT chk_usuario_rol CHECK (rol IN ('ADMIN', 'AGRONOMO', 'OPERARIO'))
);

CREATE TABLE proveedor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    cuit VARCHAR(20) NOT NULL UNIQUE,
    telefono VARCHAR(30),
    email VARCHAR(100)
);

CREATE TABLE cultivo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(60) NOT NULL UNIQUE,
    especie VARCHAR(60) NOT NULL
);

-- -----------------------------------------------------------------------------
-- 1. Tabla: LOTE
-- -----------------------------------------------------------------------------
CREATE TABLE lote (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    superficie_ha DECIMAL(10, 2) NOT NULL,
    latitud DECIMAL(10, 6) NOT NULL,
    longitud DECIMAL(10, 6) NOT NULL,
    poligono_wkt TEXT, -- Almacena GEOMETRY(POLYGON) en formato WKT para compatibilidad GIS/PostGIS
    tipo_suelo VARCHAR(50),
    estado VARCHAR(30) NOT NULL DEFAULT 'EN_PREPARACION',
    observaciones TEXT,
    usuario_id BIGINT,
    CONSTRAINT fk_lote_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE SET NULL,
    CONSTRAINT chk_lote_superficie CHECK (superficie_ha > 0),
    CONSTRAINT chk_lote_estado CHECK (estado IN ('EN_PREPARACION', 'SEMBRADO', 'EN_CRECIMIENTO', 'LISTO_COSECHA', 'COSECHADO', 'DESCANSO'))
);

-- -----------------------------------------------------------------------------
-- 2. Tabla: INSUMO
-- -----------------------------------------------------------------------------
CREATE TABLE insumo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    categoria VARCHAR(40) NOT NULL,
    unidad_medida VARCHAR(20) NOT NULL,
    stock_actual DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    stock_reservado DECIMAL(12, 2) NOT NULL DEFAULT 0.00, -- Cantidad comprometida por labores planificadas (reserva lógica)
    stock_minimo_alerta DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    precio_unitario DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    CONSTRAINT chk_insumo_categoria CHECK (categoria IN ('SEMILLA', 'FERTILIZANTE', 'FITOSANITARIO', 'COMBUSTIBLE')),
    CONSTRAINT chk_insumo_unidad CHECK (unidad_medida IN ('KILOGRAMOS', 'LITROS', 'BOLSAS', 'TONELADAS')),
    CONSTRAINT chk_insumo_stock CHECK (stock_actual >= 0),
    CONSTRAINT chk_insumo_reservado CHECK (stock_reservado >= 0 AND stock_reservado <= stock_actual),
    CONSTRAINT chk_insumo_minimo CHECK (stock_minimo_alerta >= 0),
    CONSTRAINT chk_insumo_precio CHECK (precio_unitario >= 0)
);

-- -----------------------------------------------------------------------------
-- 3. Tabla: MAQUINARIA
-- -----------------------------------------------------------------------------
CREATE TABLE maquinaria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    tipo VARCHAR(40) NOT NULL,
    matricula_o_serie VARCHAR(50) NOT NULL UNIQUE,
    horas_uso_actuales DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    horas_para_proximo_service DECIMAL(10, 2) NOT NULL,
    consumo_litros_hora DECIMAL(8, 2) NOT NULL DEFAULT 0.00,
    costo_operativo_hora DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    estado VARCHAR(30) NOT NULL DEFAULT 'OPERATIVO',
    CONSTRAINT chk_maquinaria_tipo CHECK (tipo IN ('TRACTOR', 'COSECHADORA', 'PULVERIZADORA', 'SEMBRADORA', 'VEHICULO_APOYO')),
    CONSTRAINT chk_maquinaria_estado CHECK (estado IN ('OPERATIVO', 'EN_MANTENIMIENTO', 'EN_LABOR', 'FUERA_DE_SERVICIO')),
    CONSTRAINT chk_maquinaria_horas CHECK (horas_uso_actuales >= 0)
);

-- -----------------------------------------------------------------------------
-- 4. Tabla: REGISTRO_MANTENIMIENTO
-- -----------------------------------------------------------------------------
CREATE TABLE registro_mantenimiento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    maquinaria_id BIGINT NOT NULL,
    usuario_id BIGINT,
    fecha_service DATE NOT NULL,
    horas_maquina_en_service DECIMAL(10, 2) NOT NULL,
    tipo_mantenimiento VARCHAR(40) NOT NULL,
    costo DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    proximo_service_horas DECIMAL(10, 2) NOT NULL,
    descripcion TEXT,
    CONSTRAINT fk_mantenimiento_maquinaria FOREIGN KEY (maquinaria_id) REFERENCES maquinaria (id) ON DELETE CASCADE,
    CONSTRAINT fk_mantenimiento_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE SET NULL,
    CONSTRAINT chk_mantenimiento_tipo CHECK (tipo_mantenimiento IN ('PREVENTIVO_PROGRAMADO', 'CAMBIO_ACEITE_FILTROS', 'CORRECTIVO_ROTURA')),
    CONSTRAINT chk_mantenimiento_costo CHECK (costo >= 0)
);

-- -----------------------------------------------------------------------------
-- 5. Tabla: REGLA_CLIMATICA
-- -----------------------------------------------------------------------------
CREATE TABLE regla_climatica (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_labor VARCHAR(40) NOT NULL UNIQUE,
    viento_max_kmh DECIMAL(5, 2) NOT NULL,
    viento_min_kmh DECIMAL(5, 2) NOT NULL DEFAULT 0.00,
    temp_min_c DECIMAL(5, 2) NOT NULL DEFAULT 5.00,
    temp_max_c DECIMAL(5, 2) NOT NULL DEFAULT 35.00,
    prob_lluvia_max_pct DECIMAL(5, 2) NOT NULL DEFAULT 20.00,
    humedad_min_pct DECIMAL(5, 2) NOT NULL DEFAULT 30.00,
    mensaje_alerta VARCHAR(255) NOT NULL,
    CONSTRAINT chk_regla_labor CHECK (tipo_labor IN ('PULVERIZACION', 'SIEMBRA', 'COSECHA', 'FERTILIZACION'))
);

-- -----------------------------------------------------------------------------
-- 6. Tabla: LABOR_AGRICOLA
-- -----------------------------------------------------------------------------
CREATE TABLE labor_agricola (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lote_id BIGINT NOT NULL,
    maquinaria_id BIGINT,
    usuario_id BIGINT,
    tipo_labor VARCHAR(40) NOT NULL,
    fecha_planificada TIMESTAMP NOT NULL,
    fecha_ejecucion TIMESTAMP,
    estado VARCHAR(30) NOT NULL DEFAULT 'PLANIFICADA',
    horas_maquina_consumidas DECIMAL(8, 2) DEFAULT 0.00,
    costo_total_calculado DECIMAL(12, 2) DEFAULT 0.00,
    temperatura_registrada DECIMAL(5, 2),
    viento_velocidad_kmh DECIMAL(6, 2),
    probabilidad_lluvia_pct DECIMAL(5, 2),
    humedad_registrada_pct DECIMAL(5, 2),
    observaciones_climaticas TEXT,
    CONSTRAINT fk_labor_lote FOREIGN KEY (lote_id) REFERENCES lote (id) ON DELETE RESTRICT,
    CONSTRAINT fk_labor_maquinaria FOREIGN KEY (maquinaria_id) REFERENCES maquinaria (id) ON DELETE SET NULL,
    CONSTRAINT fk_labor_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE SET NULL,
    CONSTRAINT chk_labor_tipo CHECK (tipo_labor IN ('SIEMBRA', 'PULVERIZACION', 'FERTILIZACION', 'COSECHA', 'LABRANZA')),
    CONSTRAINT chk_labor_estado CHECK (estado IN ('PLANIFICADA', 'APROBADA_CLIMA', 'BLOQUEADA_CLIMA', 'EN_EJECUCION', 'COMPLETADA', 'CANCELADA'))
);

-- -----------------------------------------------------------------------------
-- 7. Tabla: LABOR_INSUMO
-- -----------------------------------------------------------------------------
CREATE TABLE labor_insumo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    labor_id BIGINT NOT NULL,
    insumo_id BIGINT NOT NULL,
    cantidad_utilizada DECIMAL(12, 2) NOT NULL,
    costo_subtotal DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    estado_reserva VARCHAR(20) NOT NULL DEFAULT 'RESERVADO',
    CONSTRAINT fk_laborinsumo_labor FOREIGN KEY (labor_id) REFERENCES labor_agricola (id) ON DELETE CASCADE,
    CONSTRAINT fk_laborinsumo_insumo FOREIGN KEY (insumo_id) REFERENCES insumo (id) ON DELETE RESTRICT,
    CONSTRAINT chk_laborinsumo_cantidad CHECK (cantidad_utilizada > 0),
    CONSTRAINT chk_laborinsumo_costo CHECK (costo_subtotal >= 0),
    CONSTRAINT chk_laborinsumo_reserva CHECK (estado_reserva IN ('RESERVADO', 'CONSUMIDO', 'LIBERADO')),
    CONSTRAINT uq_laborinsumo UNIQUE (labor_id, insumo_id)
);

-- -----------------------------------------------------------------------------
-- 8. Tabla: REGISTRO_COSECHA
-- -----------------------------------------------------------------------------
CREATE TABLE registro_cosecha (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lote_id BIGINT NOT NULL,
    labor_id BIGINT UNIQUE,
    cultivo_id BIGINT NOT NULL,
    usuario_id BIGINT,
    fecha_cosecha DATE NOT NULL,
    toneladas_totales DECIMAL(10, 2) NOT NULL,
    rinde_ton_por_ha DECIMAL(8, 2) NOT NULL,
    precio_venta_por_ton DECIMAL(12, 2) NOT NULL,
    ingreso_bruto_total DECIMAL(14, 2) NOT NULL,
    margen_neto_calculado DECIMAL(14, 2) NOT NULL DEFAULT 0.00,
    CONSTRAINT fk_cosecha_lote FOREIGN KEY (lote_id) REFERENCES lote (id) ON DELETE RESTRICT,
    CONSTRAINT fk_cosecha_labor FOREIGN KEY (labor_id) REFERENCES labor_agricola (id) ON DELETE SET NULL,
    CONSTRAINT fk_cosecha_cultivo FOREIGN KEY (cultivo_id) REFERENCES cultivo (id) ON DELETE RESTRICT,
    CONSTRAINT fk_cosecha_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE SET NULL,
    CONSTRAINT chk_cosecha_toneladas CHECK (toneladas_totales >= 0),
    CONSTRAINT chk_cosecha_rinde CHECK (rinde_ton_por_ha >= 0),
    CONSTRAINT chk_cosecha_precio CHECK (precio_venta_por_ton >= 0)
);

-- -----------------------------------------------------------------------------
-- 9. Tablas de Compras y Movimientos de Stock
-- -----------------------------------------------------------------------------
CREATE TABLE compra_insumo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proveedor_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    fecha_compra TIMESTAMP NOT NULL,
    total_compra DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    CONSTRAINT fk_compra_proveedor FOREIGN KEY (proveedor_id) REFERENCES proveedor(id) ON DELETE RESTRICT,
    CONSTRAINT fk_compra_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE RESTRICT,
    CONSTRAINT chk_compra_total CHECK (total_compra >= 0)
);

CREATE TABLE detalle_compra (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compra_id BIGINT NOT NULL,
    insumo_id BIGINT NOT NULL,
    cantidad DECIMAL(12, 2) NOT NULL,
    precio_unitario DECIMAL(12, 2) NOT NULL,
    subtotal DECIMAL(12, 2) NOT NULL,
    CONSTRAINT fk_detalle_compra FOREIGN KEY (compra_id) REFERENCES compra_insumo(id) ON DELETE CASCADE,
    CONSTRAINT fk_detalle_insumo FOREIGN KEY (insumo_id) REFERENCES insumo(id) ON DELETE RESTRICT,
    CONSTRAINT chk_detalle_cantidad CHECK (cantidad > 0),
    CONSTRAINT chk_detalle_precio CHECK (precio_unitario >= 0)
);

CREATE TABLE movimiento_stock (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    insumo_id BIGINT NOT NULL,
    fecha TIMESTAMP NOT NULL,
    tipo VARCHAR(30) NOT NULL,
    cantidad DECIMAL(12, 2) NOT NULL,
    usuario_id BIGINT NOT NULL,
    labor_id BIGINT,
    compra_id BIGINT,
    observacion TEXT,
    CONSTRAINT fk_movimiento_insumo FOREIGN KEY (insumo_id) REFERENCES insumo(id) ON DELETE RESTRICT,
    CONSTRAINT fk_movimiento_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE RESTRICT,
    CONSTRAINT fk_movimiento_labor FOREIGN KEY (labor_id) REFERENCES labor_agricola(id) ON DELETE SET NULL,
    CONSTRAINT fk_movimiento_compra FOREIGN KEY (compra_id) REFERENCES compra_insumo(id) ON DELETE SET NULL,
    CONSTRAINT chk_movimiento_tipo CHECK (tipo IN ('INGRESO_COMPRA', 'EGRESO_LABOR', 'AJUSTE'))
);

-- -----------------------------------------------------------------------------
-- Índices para optimización de consultas recurrentes
-- -----------------------------------------------------------------------------
CREATE INDEX idx_lote_estado ON lote(estado);
CREATE INDEX idx_labor_lote ON labor_agricola(lote_id);
CREATE INDEX idx_labor_estado ON labor_agricola(estado);
CREATE INDEX idx_labor_fecha ON labor_agricola(fecha_planificada);
CREATE INDEX idx_mantenimiento_maquina ON registro_mantenimiento(maquinaria_id);
CREATE INDEX idx_cosecha_lote ON registro_cosecha(lote_id);
CREATE INDEX idx_movimiento_insumo ON movimiento_stock(insumo_id);
CREATE INDEX idx_laborinsumo_reserva ON labor_insumo(insumo_id, estado_reserva);
